main:
  concurrency: 5
  request-count: 25
  targeting-policy: "seq"  # values are: seq, parallel, round-robin

data-source: # this is a url which gets called before a target(s) execution start(s), and
             # allows you to define variables for all your targets, regardless of per-target
             # variable definitions
  url: http://127.0.0.1:3001/source
  variables:
    $username:
      type: string
      path: data.username
      $password:
        type: string
        path: data.password
  refreshMs: 0 # 0 => no refreshing, only once
               # > 0 => the number of ms interval used for refreshing the data source
targets:
  # if you define multiple targets, they get exec
  login:
    url: http://127.0.0.1:3001/login # the URL to which
    variables: # This field allows you to define variables returned by the target's response,
               # and can be used by other targets. It supports only responses in JSON format.
               # NOTE: this field is usable by other targets only if the targeting policy
               # is set to 'seq'. Because using variables is meaningful and
               # and non-buggy only if they are ready before the next target rolls in for execution
      $username:
        type: string #possible types are: string, int, array and object
        path: data.username
      $password:
        type: string
        path: data.password
    headers:
      Origin: test.com
      Content-Type: text/html
    exec-duration-header-name: ""
    cache-usage-header-name: ""
    enable-logs: true
    max-timeout: 1

  getUser:
    depends_on:
      - login
    url: http://127.0.0.1:3001/getUser
    variables:
      $name:
        type: array
        path: data.name
    headers:
      Origin: test.com
      Content-Type: text/html
    assertions:
      body-string: "'firstName' : "
    exec-duration-header-name: ""
    cache-usage-header-name: ""
    enable-logs: true
